# Generated by Django 2.0.7 on 2018-07-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnixCpuMetricPerHour',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('cpu_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('guest', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('guest_nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('iowait', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('irq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('softirq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('steal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('system', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cpu_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnixCpuMetricPerMinute',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('cpu_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('guest', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('guest_nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('iowait', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('irq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('softirq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('steal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('system', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cpu_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnixCpuMetricPerSecond',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('cpu_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('guest', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('guest_nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('iowait', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('irq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nice', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('softirq', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('steal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('system', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cpu_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('idle_time', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
