# Generated by Django 2.0.7 on 2018-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='cpu_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='guest',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='guest_nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='idle',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='idle_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='iowait',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='irq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='softirq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='steal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='system',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='total_usage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperhour',
            name='user',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='cpu_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='guest',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='guest_nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='idle',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='idle_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='iowait',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='irq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='softirq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='steal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='system',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='total_usage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricperminute',
            name='user',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='cpu_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='guest',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='guest_nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='idle',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='idle_time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='iowait',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='irq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='nice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='softirq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='steal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='system',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='total_usage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='unixcpumetricpersecond',
            name='user',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
