# Generated by Django 2.0.7 on 2018-07-12 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_auto_20180712_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnixCpuMetricPerFiveMinutes',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('cpu_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('guest', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('guest_nice', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('idle', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('iowait', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('irq', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('nice', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('softirq', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('steal', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('system', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('user', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('cpu_time', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('idle_time', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unix cpu metric per five minutes',
            },
        ),
    ]
