# Generated by Django 2.0.7 on 2018-07-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0005_unixcpumetricperfiveminutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unixcpumetricperfiveminutes',
            name='cpu_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricperfiveminutes',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricperhour',
            name='cpu_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricperhour',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricperminute',
            name='cpu_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricperminute',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricpersecond',
            name='cpu_time',
        ),
        migrations.RemoveField(
            model_name='unixcpumetricpersecond',
            name='idle_time',
        ),
    ]
